<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsX2So3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsX2So3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPsX2So3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPsX2So3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPsX2So3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PsX2So3',
    'container.build_id' => '9097bafa',
    'container.build_time' => 1591186322,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsX2So3');
