<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR4qxXJs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR4qxXJs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR4qxXJs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR4qxXJs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR4qxXJs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R4qxXJs',
    'container.build_id' => '44394b62',
    'container.build_time' => 1591177087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR4qxXJs');
