<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKOvth1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKOvth1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKOvth1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKOvth1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWKOvth1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WKOvth1',
    'container.build_id' => '59cdc193',
    'container.build_time' => 1591197179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKOvth1');
